<?php
/**
 * Foundation data validation commands for validating exported content from Foundation.
 *
 * @package NewspackCustomContentMigrator
 */

namespace NewspackCustomContentMigrator\Command\General\Foundation;

use Newspack\MigrationTools\Command\WpCliCommandTrait;
use NewspackCustomContentMigrator\Command\RegisterCommandInterface;
use Newspack\MigrationTools\Util\JsonIterator;
use Newspack\MigrationTools\Util\Log\MultiLog;
use WP_CLI;

class FoundationDataValidation implements RegisterCommandInterface {

	use WpCliCommandTrait;

	/**
	 * JSON iterator.
	 *
	 * @var JsonIterator
	 */
	private JsonIterator $json_iterator;

	/**
	 * Logger.
	 *
	 * @var MultiLog
	 */
	private MultiLog $logger;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->json_iterator = new JsonIterator();
		$this->logger        = MultiLog::get_cli_and_file_logger( 'foundation-validate-data' );
	}

	/**
	 * {@inheritDoc}
	 */
	public static function register_commands(): void {
		WP_CLI::add_command(
			'newspack-content-migrator foundation-validate-taxonomies',
			self::get_command_closure( 'cmd_validate_taxonomies' ),
			[
				'shortdesc' => 'Validates Foundation taxonomies received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'category-json-file',
						'description' => 'Path to the JSON file containing the taxonomies (e.g. `Category.json`). The JSON file generated by Foundation contains all taxonomies, including categories and tags. despite its name.',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);

		WP_CLI::add_command(
			'newspack-content-migrator foundation-validate-users',
			self::get_command_closure( 'cmd_validate_users' ),
			[
				'shortdesc' => 'Validates Foundation users received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'wp-author-json-file',
						'description' => 'Path to the JSON file containing the authors (e.g. `WPAuthor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-contributor-json-file',
						'description' => 'Path to the JSON file containing the contributors (e.g. `WPContributor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-editor-json-file',
						'description' => 'Path to the JSON file containing the editors (e.g. `WPEditor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-comment-author-json-file',
						'description' => 'Path to the JSON file containing the comment authors (e.g. `WPCommentAuthor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);

		WP_CLI::add_command(
			'newspack-content-migrator foundation-validate-content',
			self::get_command_closure( 'cmd_validate_content' ),
			[
				'shortdesc' => 'Validates Foundation content received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'post-json-file',
						'description' => 'Path to the JSON file containing the posts (e.g. `Post.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'page-json-file',
						'description' => 'Path to the JSON file containing the pages (e.g. `Page.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'slideshow-json-file',
						'description' => 'Path to the JSON file containing the slideshows (e.g. `Slideshow.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'comment-json-file',
						'description' => 'Path to the JSON file containing the comments (e.g. `Comment.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);
	}

	/**
	 * Validates Foundation taxonomies received from their export.
	 * Callable for 'newspack-content-migrator foundation-validate-taxonomies' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_validate_taxonomies( array $args, array $assoc_args ): void {
		$category_json_file = $assoc_args['category-json-file'];

		$taxonomies = $this->json_iterator->items( $category_json_file );

		$categories_count = 0;
		$tags_count       = 0;

		foreach ( $taxonomies as $taxonomy ) {
			if ( in_array( $taxonomy->class, [ 'Category', 'Section' ], true ) ) {
				++$categories_count;
			} elseif ( 'Tag' === $taxonomy['class'] ) {
				++$tags_count;
			}
		}

		$this->logger->info( sprintf( 'Found %d categories and %d tags.', $categories_count, $tags_count ) );
	}

	/**
	 * Validates Foundation users received from their export.
	 * Callable for 'newspack-content-migrator foundation-validate-users' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_validate_users( array $args, array $assoc_args ): void {
		$wp_author_json_file         = $assoc_args['wp-author-json-file'];
		$wp_contributor_json_file    = $assoc_args['wp-contributor-json-file'];
		$wp_editor_json_file         = $assoc_args['wp-editor-json-file'];
		$wp_comment_author_json_file = $assoc_args['wp-comment-author-json-file'];

		$authors         = $this->json_iterator->count_json_array_entries( $wp_author_json_file );
		$contributors    = $this->json_iterator->count_json_array_entries( $wp_contributor_json_file );
		$editors         = $this->json_iterator->count_json_array_entries( $wp_editor_json_file );
		$comment_authors = $this->json_iterator->count_json_array_entries( $wp_comment_author_json_file );

		$this->logger->info( sprintf( 'Found %d authors, %d contributors, %d editors and %d comment authors.', $authors, $contributors, $editors, $comment_authors ) );
	}

	/**
	 * Validates Foundation content received from their export.
	 * Callable for 'newspack-content-migrator foundation-validate-content' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_validate_content( array $args, array $assoc_args ): void {
		$post_json_file      = $assoc_args['post-json-file'];
		$page_json_file      = $assoc_args['page-json-file'];
		$slideshow_json_file = $assoc_args['slideshow-json-file'];
		$comment_json_file   = $assoc_args['comment-json-file'];

		$posts      = $this->json_iterator->count_json_array_entries( $post_json_file );
		$pages      = $this->json_iterator->count_json_array_entries( $page_json_file );
		$slideshows = $this->json_iterator->count_json_array_entries( $slideshow_json_file );
		$comments   = $this->json_iterator->count_json_array_entries( $comment_json_file );

		$this->logger->info( sprintf( 'Found %d posts, %d pages, %d slideshows and %d comments.', $posts, $pages, $slideshows, $comments ) );
	}
}
