<?php
/**
 * Foundation data migration commands for migrating exported content from Foundation.
 *
 * @phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
 *
 * @package NewspackCustomContentMigrator
 */

namespace NewspackCustomContentMigrator\Command\General\Foundation;

use Newspack\MigrationTools\Command\WpCliCommandTrait;
use NewspackCustomContentMigrator\Command\RegisterCommandInterface;
use Newspack\MigrationTools\Logic\GuestContributorsHelper;
use Newspack\MigrationTools\Logic\Attachments;
use Newspack\MigrationTools\Logic\Taxonomy;
use Newspack\MigrationTools\Logic\SimpleLocalAvatars;
use Newspack\MigrationTools\Logic\UsersHelper;
use Newspack\MigrationTools\Logic\GutenbergBlockGenerator;
use Newspack\MigrationTools\Logic\Posts;
use Newspack\MigrationTools\Util\JsonIterator;
use Newspack\MigrationTools\Util\Log\MultiLog;
use Newspack\MigrationTools\Util\CsvWriter;
use WP_CLI;

class FoundationMigrator implements RegisterCommandInterface {

	use WpCliCommandTrait;

	/**
	 * JSON iterator.
	 *
	 * @var null|SJsonIterator
	 */
	private JsonIterator $json_iterator;

	/**
	 * Taxonomy logic.
	 *
	 * @var null|STaxonomy
	 */
	private Taxonomy $taxonomy_logic;

	/**
	 * Gutenberg block generator.
	 *
	 * @var null|GutenbergBlockGenerator
	 */
	private GutenbergBlockGenerator $gutenberg_block_generator;

	/**
	 * Instance of SimpleLocalAvatars.
	 *
	 * @var null|SimpleLocalAvatars
	 */
	private $simple_local_avatars_logic;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->json_iterator              = new JsonIterator();
		$this->taxonomy_logic             = new Taxonomy();
		$this->gutenberg_block_generator  = new GutenbergBlockGenerator();
		$this->simple_local_avatars_logic = new SimpleLocalAvatars();
	}

	/**
	 * {@inheritDoc}
	 */
	public static function register_commands(): void {
		WP_CLI::add_command(
			'newspack-content-migrator foundation-migrate-taxonomies',
			self::get_command_closure( 'cmd_migrate_taxonomies' ),
			[
				'shortdesc' => 'Migrates Foundation taxonomies received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'category-json-file',
						'description' => 'Path to the JSON file containing the taxonomies (e.g. `Category.json`). The JSON file generated by Foundation contains all taxonomies, including categories and tags. despite its name.',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);

		WP_CLI::add_command(
			'newspack-content-migrator foundation-migrate-users',
			self::get_command_closure( 'cmd_migrate_users' ),
			[
				'shortdesc' => 'Migrates Foundation users received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'wp-author-json-file',
						'description' => 'Path to the JSON file containing the authors (e.g. `WPAuthor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-contributor-json-file',
						'description' => 'Path to the JSON file containing the contributors (e.g. `WPContributor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-editor-json-file',
						'description' => 'Path to the JSON file containing the editors (e.g. `WPEditor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'wp-comment-author-json-file',
						'description' => 'Path to the JSON file containing the comment authors (e.g. `WPCommentAuthor.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);

		WP_CLI::add_command(
			'newspack-content-migrator foundation-migrate-posts',
			self::get_command_closure( 'cmd_migrate_posts' ),
			[
				'shortdesc' => 'Migrates Foundation posts received from their export.',
				'synopsis'  => [
					[
						'type'        => 'assoc',
						'name'        => 'post-json-file',
						'description' => 'Path to the JSON file containing the posts (e.g. `Post.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'image-json-file',
						'description' => 'Path to the JSON file containing the images (e.g. `Image.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'embed-json-file',
						'description' => 'Path to the JSON file containing the embeds (e.g. `Embed.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'audio-json-file',
						'description' => 'Path to the JSON file containing the audio (e.g. `Audio.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
					[
						'type'        => 'assoc',
						'name'        => 'pdf-json-file',
						'description' => 'Path to the JSON file containing the pdfs (e.g. `PDF.json`).',
						'optional'    => false,
						'repeating'   => false,
					],
				],
			]
		);
	}

	/**
	 * Migrates Foundation taxonomies received from their export.
	 * Callable for 'newspack-content-migrator foundation-migrate-taxonomies' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_migrate_taxonomies( array $args, array $assoc_args ): void {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$category_json_file = $assoc_args['category-json-file'];

		$logger->info( sprintf( 'Migrating taxonomies from %s', $category_json_file ) );

		$raw_sections   = $this->json_iterator->filtered_items( $category_json_file, 'class', 'Section' );
		$raw_categories = $this->json_iterator->filtered_items( $category_json_file, 'class', 'Category' );
		$raw_tags       = $this->json_iterator->filtered_items( $category_json_file, 'class', 'Tag' );

		$migrated_sections   = [];
		$migrated_categories = [];
		$migrated_tags       = [];

		// Migrate sections (main categories).
		foreach ( $raw_sections as $section ) {
			$migrated_section = $this->taxonomy_logic->get_or_create_category(
				[
					'cat_name'             => $section->name,
					'category_description' => $section->description,
					'category_nicename'    => $section->id,
					'category_parent'      => 0,
				],
				$section->oid
			);

			if ( is_wp_error( $migrated_section ) ) {
				$logger->error( sprintf( 'Error migrating section %s: %s', $section->name, $migrated_section->get_error_message() ) );
				continue;
			}

			$migrated_sections[ $section->oid ] = $migrated_section;
			$logger->info( sprintf( 'Migrated section %s with ID %d', $section->name, $migrated_section ) );
		}

		// Migrate categories.
		foreach ( $raw_categories as $category ) {
			$parent_id = 0;
			if ( isset( $category->section ) ) {
				if ( isset( $migrated_sections[ $category->section ] ) ) {
					$parent_id = $migrated_sections[ $category->section ];
				} else {
					$logger->error( sprintf( 'Section %s not found', $category->section ) );
					continue;
				}
			}

			// TODO: Migrate category image as part of the category description.
			$migrated_category = $this->taxonomy_logic->get_or_create_category(
				[
					'cat_name'             => $category->name,
					'category_description' => $category->description,
					'category_nicename'    => $category->id,
					'category_parent'      => $parent_id,
				],
				$category->oid
			);

			if ( is_wp_error( $migrated_category ) ) {
				$logger->error( sprintf( 'Error migrating category %s: %s', $category->name, $migrated_category->get_error_message() ) );
				continue;
			}

			$migrated_categories[ $category->oid ] = $migrated_category;
			$logger->info( sprintf( 'Migrated category %s with ID %d', $category->name, $migrated_category ) );
		}

		// Migrate tags.
		foreach ( $raw_tags as $tag ) {
			// TODO: Migrate tags.
			$logger->info( sprintf( 'Migrating tags %s', $tag->name ) );
		}

		$logger->info( sprintf( 'Migrated %d sections, %d categories and %d tags', count( $migrated_sections ), count( $migrated_categories ), count( $migrated_tags ) ) );
	}

	/**
	 * Migrates Foundation users received from their export.
	 * Callable for 'newspack-content-migrator foundation-migrate-users' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_migrate_users( array $args, array $assoc_args ): void {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$wp_author_json_file         = $assoc_args['wp-author-json-file'];
		$wp_contributor_json_file    = $assoc_args['wp-contributor-json-file'];
		$wp_editor_json_file         = $assoc_args['wp-editor-json-file'];
		$wp_comment_author_json_file = $assoc_args['wp-comment-author-json-file'];

		$logger->info( sprintf( 'Migrating users from %s, %s, %s and %s', $wp_author_json_file, $wp_contributor_json_file, $wp_editor_json_file, $wp_comment_author_json_file ) );

		$raw_authors         = $this->json_iterator->items( $wp_author_json_file );
		$raw_contributors    = $this->json_iterator->items( $wp_contributor_json_file );
		$raw_editors         = $this->json_iterator->items( $wp_editor_json_file );
		$raw_comment_authors = $this->json_iterator->items( $wp_comment_author_json_file );

		$migrated_authors         = [];
		$migrated_contributors    = [];
		$migrated_editors         = [];
		$migrated_comment_authors = [];

		// Migrate authors.
		foreach ( $raw_authors as $author ) {
			// TODO: Once we have an sample of this data.
		}

		// Migrate contributors.
		foreach ( $raw_contributors as $contributor ) {
			$contributor_data     = [
				'user_login'   => $contributor->username,
				'user_email'   => $contributor->email,
				'display_name' => $contributor->displayName,
				'user_url'     => $contributor->website,
				'meta_input'   => [
					'description' => $contributor->bio,
					'facebook'    => $contributor->facebookUrl,
					'instagram'   => $contributor->instagramUrl,
					'linkedin'    => $contributor->linkedinUrl,
					'twitter'     => $contributor->twitterUrl,
					'youtube'     => $contributor->youtubeUrl,
					'bluesky'     => $contributor->blueskyUrl,
				],
			];
			$migrated_contributor = GuestContributorsHelper::create_or_get_contributor( $contributor_data, $contributor->oid );

			if ( is_wp_error( $migrated_contributor ) ) {
				$logger->error( sprintf( 'Error migrating contributor %s: %s', $contributor->oid, $migrated_contributor->get_error_message() ) );
				continue;
			}

			// Upload and set avatar if available.
			if ( isset( $contributor->image ) && ! empty( $contributor->image ) ) {
				$avatar_id = Attachments::import_external_file( $contributor->image );
				if ( is_wp_error( $avatar_id ) ) {
					$logger->error( sprintf( 'Error importing avatar for contributor %s: %s', $contributor->oid, $avatar_id->get_error_message() ) );
				}

				$this->simple_local_avatars_logic->assign_avatar( $migrated_contributor->ID, $avatar_id );
			}

			$migrated_contributors[ $contributor->oid ] = $migrated_contributor->ID;
			$logger->info( sprintf( 'Migrated contributor %s with ID %d', $contributor->oid, $migrated_contributor->ID ) );
		}

		// Migrate editors.
		foreach ( $raw_editors as $editor ) {
			$editor_data     = [
				'role'          => 'editor',
				'user_login'    => $editor->username,
				'user_email'    => $editor->email,
				'display_name'  => $editor->name,
				'user_nicename' => $editor->basename ?? '',
				'user_url'      => $editor->website ?? '',
				'meta_input'    => [
					'description'           => $this->migrate_user_bio( $editor ),
					'newspack_phone_number' => $editor->phone ?? '',
					'facebook'              => $editor->facebookUrl ?? '',
					'instagram'             => $editor->instagramUrl ?? '',
					'linkedin'              => $editor->linkedinUrl ?? '',
					'twitter'               => $editor->twitterUrl ?? '',
					'youtube'               => $editor->youtubeUrl ?? '',
					'bluesky'               => $editor->blueskyUrl ?? '',
				],
			];
			$migrated_editor = UsersHelper::create_or_get_user( $editor_data, $editor->oid );

			if ( is_wp_error( $migrated_editor ) ) {
				$logger->error( sprintf( 'Error migrating editor %s: %s', $editor->oid, $migrated_editor->get_error_message() ) );
				continue;
			}

			// Upload and set avatar if available.
			if ( isset( $editor->image ) && ! empty( $editor->image ) ) {
				$avatar_id = Attachments::import_external_file( $editor->image );
				if ( is_wp_error( $avatar_id ) ) {
					$logger->error( sprintf( 'Error importing avatar for editor %s: %s', $editor->oid, $avatar_id->get_error_message() ) );
				}

				$this->simple_local_avatars_logic->assign_avatar( $migrated_editor->ID, $avatar_id );
			}

			$migrated_editors[ $editor->oid ] = $migrated_editor->ID;
			$logger->info( sprintf( 'Migrated editor %s with ID %d', $editor->oid, $migrated_editor->ID ) );
		}

		// Migrate comment authors.
		foreach ( $raw_comment_authors as $comment_author ) {
			// TODO: Once we have an sample of this data.
		}

		$logger->info( sprintf( 'Migrated %d authors, %d contributors, %d editors and %d comment authors', count( $migrated_authors ), count( $migrated_contributors ), count( $migrated_editors ), count( $migrated_comment_authors ) ) );
	}

	/**
	 * Migrates Foundation posts received from their export.
	 * Callable for 'newspack-content-migrator foundation-migrate-posts' command.
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function cmd_migrate_posts( array $args, array $assoc_args ): void {
		$next_time = microtime( true );

		global $wpdb;

		$logger     = MultiLog::get_cli_and_file_logger( __FUNCTION__ );
		$csv_writer = new CsvWriter( __FUNCTION__ . '.csv' );
		$csv_writer->set_header( [ 'oid', 'post_id', 'old_url', 'new_url' ] );

		$post_json_file  = $assoc_args['post-json-file'];
		$image_json_file = $assoc_args['image-json-file'];
		$embed_json_file = $assoc_args['embed-json-file'];
		$audio_json_file = $assoc_args['audio-json-file'];
		$pdf_json_file   = $assoc_args['pdf-json-file'];

		$raw_posts = $this->json_iterator->items( $post_json_file );

		$logger->info( sprintf( '%s took %s seconds', 'load files', round( microtime( true ) - $next_time, 2 ) ) );
		$next_time = microtime( true );

		$migrated_posts = [];

		foreach ( $raw_posts as $post ) {
			$mapped_authors    = $this->map_authors( $post->authors );
			$mapped_categories = $this->map_categories( $post->categories );
			$mapped_topics     = $this->map_categories( $post->topics );
			$post_categories   = array_values( array_merge( $mapped_categories, $mapped_topics ) );

			$logger->info( sprintf( '%s took %s seconds', 'map authors/categories', round( microtime( true ) - $next_time, 2 ) ) );
			$next_time = microtime( true );

			// Check if the post has non migrated authors.
			if ( count( $mapped_authors ) !== count( array_unique( $post->authors ) ) ) {
				$logger->error( sprintf( 'Skipping post %d because it has non migrated authors: %s', $post->oid, implode( ', ', array_diff( $post->authors, array_keys( $mapped_authors ) ) ) ) );
				// continue;
			}

			// Check if the post has non migrated categories.
			if ( count( $mapped_categories ) !== count( array_unique( $post->categories ) ) ) {
				$logger->error( sprintf( 'Post %d has non migrated categories: %s', $post->oid, implode( ', ', array_diff( $post->categories, array_keys( $post_categories ) ) ) ) );
			}

			// Check if the post has non migrated topics.
			if ( count( $mapped_topics ) !== count( array_unique( $post->topics ) ) ) {
				$logger->error( sprintf( 'Post %d has non migrated topics: %s', $post->oid, implode( ', ', array_diff( $post->topics, array_keys( $mapped_topics ) ) ) ) );
			}

			$release_date = new \DateTime( $post->releaseDate );
			$updated_date = new \DateTime( $post->updateDate );

			$post_data = [
				'post_type'         => 'post',
				'post_title'        => $post->headline,
				'post_name'         => $post->basename . '-' . $post->oid,
				'post_status'       => $this->map_post_status( $post->status ),
				'post_date'         => $release_date->format( 'Y-m-d H:i:s' ),
				'post_date_gmt'     => $release_date->setTimezone( new \DateTimeZone( 'UTC' ) )->format( 'Y-m-d H:i:s' ),
				'post_modified'     => $updated_date->format( 'Y-m-d H:i:s' ),
				'post_modified_gmt' => $updated_date->setTimezone( new \DateTimeZone( 'UTC' ) )->format( 'Y-m-d H:i:s' ),
				'post_content'      => $post->body,
				'post_category'     => $post_categories,
				'tags_input'        => $post->tags,
			];

			$logger->info( sprintf( '%s took %s seconds', 'generate post initial data', round( microtime( true ) - $next_time, 2 ) ) );
			$next_time        = microtime( true );
			$migrated_post_id = Posts::create_or_get_post( $post_data, $post->oid );
			$logger->info( sprintf( '%s took %s seconds', 'create post', round( microtime( true ) - $next_time, 2 ) ) );
			$next_time = microtime( true );

			if ( is_wp_error( $migrated_post_id ) ) {
				$logger->error( sprintf( 'Error migrating post %d: %s', $post->oid, $migrated_post_id->get_error_message() ) );
				continue;
			}

			// Assign contributors.
			GuestContributorsHelper::assign_contributors_to_post( $migrated_post_id, array_values( $mapped_authors ) );

			// Migrate images tray and featured image.
			$migrated_images = $this->migrate_images_tray_and_featured_image( $migrated_post_id, $post->imageLinks, $image_json_file );
			$logger->info( sprintf( '%s took %s seconds', 'migrate images tray and featured image', round( microtime( true ) - $next_time, 2 ) ) );
			$next_time = microtime( true );

			// Migrate post content.
			$updated_content = $this->generate_post_content( $migrated_post_id, $post, $migrated_images, $embed_json_file, $audio_json_file, $pdf_json_file );
			$logger->info( sprintf( '%s took %s seconds', 'generate post content', round( microtime( true ) - $next_time, 2 ) ) );
			$next_time = microtime( true );

			if ( $updated_content !== $post->body ) {
				// @phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
				$wpdb->update(
					$wpdb->posts,
					[ 'post_content' => $updated_content ],
					[ 'ID' => $migrated_post_id ]
				);
				$logger->info( sprintf( '%s took %s seconds', 'update post content', round( microtime( true ) - $next_time, 2 ) ) );
				$next_time = microtime( true );

				// If the first block is an image, hide the featured image.
				$content_blocks = parse_blocks( $updated_content );
				if ( isset( $content_blocks[0]['blockName'] ) && 'core/image' === $content_blocks[0]['blockName'] ) {
					update_post_meta( $migrated_post_id, 'newspack_featured_image_position', 'hidden' );
				}
			}

			// Setting the post's primary category.
			if ( ! empty( $post->primaryCategory ) ) {
				if ( ! array_key_exists( $post->primaryCategory, $mapped_categories ) ) {
					$logger->error( sprintf( 'Post %d has non migrated primary category: %s', $post->oid, $post->primaryCategory ) );
				} else {
					$primary_category_id = $mapped_categories[ $post->primaryCategory ];
					update_post_meta( $migrated_post_id, '_yoast_wpseo_primary_category', $primary_category_id );
				}
			}

			// Setting post meta.
			update_post_meta( $migrated_post_id, 'foundation_post_transfer', $post->transfer );
			update_post_meta( $migrated_post_id, 'foundation_post_source', $post->source );

			$migrated_posts[ $post->oid ] = $migrated_post_id;

			$csv_writer->put( [ $post->oid, $migrated_post_id, 'https://www.okgazette.com' . $post->permalink, get_permalink( $migrated_post_id ) ] );

			$logger->info( sprintf( 'Migrated post %d with ID %d', $post->oid, $migrated_post_id ) );
			$logger->info( sprintf( '%s took %s seconds', 'migrate post', round( microtime( true ) - $next_time, 2 ) ) );
			$logger->info( '+============================+' );
			$next_time = microtime( true );
		}

		$csv_writer->close();
	}

	/**
	 * Strips container divs robustly.
	 *
	 * @param string $html The HTML content to process.
	 * @return string The processed HTML content.
	 */
	private function strip_container_div_robust( string $html ): string {
		// Trim whitespace.
		$html = trim( $html );

		// Keep processing until no more attribute-less divs are found.
		$previous_length = 0;
		$current_length  = strlen( $html );
		while ( $current_length !== $previous_length ) {
			$previous_length = $current_length;
			$html            = $this->strip_attribute_less_divs( $html );
			$current_length  = strlen( $html );
		}

		return $html;
	}

	/**
	 * Helper function to strip one level of attribute-less divs.
	 *
	 * @param string $html The HTML content to process.
	 * @return string The processed HTML content.
	 */
	private function strip_attribute_less_divs( string $html ): string {
		// Use regex to find and replace attribute-less divs.
		// This pattern matches <div>content</div> where div has no attributes.
		$pattern = '/<div(?:\s+[^>]*)?>(.*?)<\/div>/s';

		// Keep replacing until no more matches.
		$previous_html = '';
		while ( $html !== $previous_html ) {
			$previous_html = $html;
			$html          = preg_replace_callback(
				$pattern,
				function ( $matches ) {
					// Check if the div tag has attributes.
					$div_tag         = $matches[0];
					$div_start       = strpos( $div_tag, '<div' );
					$div_end         = strpos( $div_tag, '>', $div_start );
					$div_tag_content = substr( $div_tag, $div_start, $div_end - $div_start + 1 );

					// If div has attributes (like class, id, style, etc.), keep it.
					if ( preg_match( '/<div\s+[^>]*>/', $div_tag_content ) ) {
						return $matches[0]; // Return unchanged.
					}

					// If div has no attributes, return just the content.
					return $matches[1];
				},
				$html
			);
		}

		return $html;
	}

	/**
	 * Generates post content.
	 *
	 * @param int    $post_id   Post ID.
	 * @param object $post Foundation post.
	 * @param array  $migrated_images Migrated images.
	 * @param string $embed_json_file Raw embeds file.
	 * @param string $audio_json_file Raw audios file.
	 * @param string $pdf_json_file   Raw PDFs file.
	 *
	 * @return string Post content.
	 */
	private function generate_post_content( int $post_id, object $post, array $migrated_images, string $embed_json_file, string $audio_json_file, string $pdf_json_file ): string {
		// TODO: Remove logger.
		$logger  = MultiLog::get_cli_and_file_logger( __FUNCTION__ );
		$content = $this->strip_container_div_robust( $post->body );

		// Migrate info box.
		$content = $this->migrate_info_box( $post->oid, $content, $post->infoBoxTitle, $post->infoBoxText, $post->infoBoxPosition );

		// Migrate images.
		$content = $this->migrate_images_markers( $post->oid, $content, $migrated_images, $post->imageLinks );

		// Migrate pullquote.
		if ( ! empty( $post->pullquotes ) ) {
			$content = $this->migrate_pullquote_markers( $post->oid, $content, $post->pullquotes );
		}

		// Migrate slideshow.
		if ( ! empty( $post->slideshow ) ) {
			echo 1;
			// TODO: Migrate slideshow.
		}

		// Migrate embed.
		if ( ! empty( $post->embed ) ) {
			$logger->info( sprintf( 'Migrating embeds for post %s', $post->oid ) );
			$content = $this->migrate_embed_markers( $post->oid, $content, $embed_json_file, $post->embed );
		}

		// Migrate audio.
		if ( ! empty( $post->audio ) ) {
			$logger->info( sprintf( 'Migrating audio for post %s', $post->oid ) );
			$content = $this->migrate_audio_markers( $post->oid, $post_id, $content, $audio_json_file, $post->audio );
		}

		// Migrate pdf.
		if ( ! empty( $post->pdf ) ) {
			$logger->info( sprintf( 'Migrating PDFs for post %s', $post->oid ) );
			$content = $this->migrate_pdf_markers( $post->oid, $post_id, $content, $pdf_json_file, $post->pdf );
		}

		return $content;
	}

	/**
	 * Migrate info box.
	 *
	 * @param string $post_oid Post OID.
	 * @param string $content Post content.
	 * @param string $info_box_title Info box title.
	 * @param string $info_box_text Info box text.
	 * @param string $info_box_position Info box position.
	 *
	 * @return string Post content with info box.
	 */
	private function migrate_info_box( string $post_oid, string $content, string $info_box_title, string $info_box_text, string $info_box_position ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		if ( ! empty( $info_box_title ) && ! empty( $info_box_text ) && ! empty( $info_box_position ) ) {
			$info_box_block = serialize_block(
				$this->gutenberg_block_generator->get_group_constrained(
					[ $this->gutenberg_block_generator->get_html( $info_box_title . $info_box_text ) ],
					[ 'newspack-embed-info-box', 'alignright' ],
					[ 'align' => 'right' ]
				)
			);

			switch ( $info_box_position ) {
				case 'top':
					return $info_box_block . $content;
				case 'bottom':
					return $content . $info_box_block;
				default:
					$logger->warning( sprintf( 'Info box position %s not supported for post %s', $info_box_position, $post_oid ) );
					return $content;
			}
		}

		return $content;
	}

	/**
	 * Migrate images tray and featured image.
	 *
	 * The featured image is the image with "Teaser" placement. The "first" image is also the default Teaser if a Teaser isn't set.
	 *
	 * @param int    $post_id      Post ID.
	 * @param array  $post_image_oids  Post image OIDs.
	 * @param string $raw_images_file Raw images file.
	 *
	 * @return array Migrated images. A key-value pair of post image OID and an array with the raw image data and the attachment ID.
	 */
	private function migrate_images_tray_and_featured_image( int $post_id, array $post_image_oids, string $raw_images_file ): array {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		if ( empty( $post_image_oids ) ) {
			return [];
		}

		$migrated_images           = [];
		$possible_teaser_image_ids = [];

		foreach ( $post_image_oids as $post_image_oid ) {
			$possible_raw_images = iterator_to_array( $this->json_iterator->filtered_items( $raw_images_file, 'oid', $post_image_oid ) );

			if ( 1 === count( $possible_raw_images ) ) {
				$raw_image     = $possible_raw_images[0];
				$attachment_id = $this->migrate_raw_attachment( $raw_image, $post_id );

				if ( is_wp_error( $attachment_id ) ) {
					$logger->error( sprintf( 'Error migrating image %s for post %s: %s', $post_image_oid, $post_id, $attachment_id->get_error_message() ) );
					continue;
				}

				$migrated_images[ $post_image_oid ] = [
					...(array) $raw_image,
					'attachment_id' => $attachment_id,
				];

				if ( isset( $raw_image->placements ) && in_array( 'teaser', $raw_image->placements, true ) ) {
					$possible_teaser_image_ids[] = $attachment_id;
				}
			} else {
				$logger->warning( sprintf( 'Image %s not found in raw images for post %s', $post_image_oid, $post_id ) );
			}
		}

		// Warn if there are multiple teaser images.
		if ( count( $possible_teaser_image_ids ) > 1 ) {
			$logger->warning( sprintf( 'Post %s has multiple teaser images: %s', $post_id, implode( ', ', $possible_teaser_image_ids ) ) );
		}

		// Set the featured image.
		if ( ! empty( $possible_teaser_image_ids ) ) {
			set_post_thumbnail( $post_id, $possible_teaser_image_ids[0] );
		} elseif ( ! empty( $migrated_images ) ) {
			set_post_thumbnail( $post_id, current( $migrated_images ) );
		}

		return $migrated_images;
	}

	/**
	 * Migrate images markers.
	 *
	 * Image markers in the content are in the format: [image-N] where N is a 1-based index.
	 * For example: [image-1] refers to the first image, [image-2] to the second, etc.
	 * This method converts these 1-based indices to 0-based indices for array access.
	 *
	 * @param string $post_oid     Post OID.
	 * @param string $content      Post content.
	 * @param array  $migrated_images   Migrated images. A key-value pair of post image OID and an array with the raw image data and the attachment ID.
	 * @param array  $post_image_oids  Post image OIDs. A 0-based indexed array.
	 *
	 * @return string Post content with image markers replaced by Gutenberg blocks.
	 */
	private function migrate_images_markers( string $post_oid, string $content, array $migrated_images, array $post_image_oids ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$content = preg_replace_callback(
			'/\[image-(\d+)\]/',
			function ( $matches ) use ( $post_oid, $migrated_images, $logger, $post_image_oids ) {
				$image_index = (int) $matches[1] - 1; // Convert to 0-based index.
				if ( ! isset( $migrated_images[ $post_image_oids[ $image_index ] ] ) ) {
					$logger->warning( sprintf( 'Image %d not found in post images for post %s', (int) $matches[1], $post_oid ) );
					return $matches[0];
				}
				$raw_image = $migrated_images[ $post_image_oids[ $image_index ] ];

				$attachment_post = get_post( $raw_image['attachment_id'] );

				if ( ! $attachment_post ) {
					$logger->warning( sprintf( 'Attachment post %d not found for image %d in post %s', $raw_image['attachment_id'], (int) $matches[1], $post_oid ) );
					return $matches[0];
				}

				$classes = '';
				if ( ! empty( $raw_image['alignment'] ) ) {
					$classes = 'align' . strtolower( $raw_image['alignment'] );
				}

				return serialize_block( $this->gutenberg_block_generator->get_image( $attachment_post, 'full', true, $classes, strtolower( $raw_image['alignment'] ), $raw_image['destinationURL'] ) );
			},
			$content
		);

		return $content;
	}

	/**
	 * Migrate pullquote markers.
	 *
	 * Pullquote markers in the content are in the format: [pullquote-N] where N is a 1-based index.
	 * For example: [pullquote-1-center] refers to the first pullquote, [pullquote-2] to the second, etc.
	 * This method converts these 1-based indices to 0-based indices for array access.
	 *
	 * @param string $post_oid        Post OID.
	 * @param string $content         Post content.
	 * @param array  $post_pullquotes Post pullquotes array (0-based indexed).
	 *
	 * @return string Post content with pullquote markers replaced by their content.
	 */
	private function migrate_pullquote_markers( string $post_oid, string $content, array $post_pullquotes ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$content = preg_replace_callback(
			'/\[pullquote-(\d+)-(\w+)\]/',
			function ( $matches ) use ( $post_oid, $logger, $post_pullquotes ) {
				$pullquote_index = (int) $matches[1] - 1; // Convert to 0-based index.
				if ( ! isset( $post_pullquotes[ $pullquote_index ] ) ) {
					$logger->warning( sprintf( 'Pullquote %d not found in post pullquotes for post %s', (int) $matches[1], $post_oid ) );
					return $matches[0];
				}
				return serialize_block( $this->gutenberg_block_generator->get_quote( $post_pullquotes[ $pullquote_index ] ) );
			},
			$content
		);

		return $content;
	}

	/**
	 * Migrate embed markers.
	 *
	 * Embed markers in the content are in the format: [embed-N] where N is a 1-based index.
	 * For example: [embed-1] refers to the first embed, [embed-2] to the second, etc.
	 * This method converts these 1-based indices to 0-based indices for array access.
	 *
	 * @param string $post_oid    Post OID.
	 * @param string $content     Post content.
	 * @param string $embed_json_file Raw embeds file.
	 * @param array  $post_embeds Post embeds array (0-based indexed).
	 *
	 * @return string Post content with embed markers replaced by Gutenberg blocks.
	 */
	private function migrate_embed_markers( string $post_oid, string $content, string $embed_json_file, array $post_embeds ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$content = preg_replace_callback(
			'/\[embed-(\d+)\]/',
			function ( $matches ) use ( $post_oid, $embed_json_file, $logger, $post_embeds ) {
				$embed_index = (int) $matches[1] - 1; // Convert to 0-based index.
				if ( ! isset( $post_embeds[ $embed_index ] ) ) {
					$logger->warning( sprintf( 'Embed %d not found in post embeds for post %s', (int) $matches[1], $post_oid ) );
					return $matches[0];
				}
				$embed_id            = $post_embeds[ $embed_index ];
				$possible_raw_embeds = iterator_to_array( $this->json_iterator->filtered_items( $embed_json_file, 'oid', $embed_id ) );

				if ( 1 === count( $possible_raw_embeds ) ) {
					$raw_embed      = $possible_raw_embeds[0];
					$migrated_embed = $this->migrate_raw_embed( $raw_embed );

					if ( is_wp_error( $migrated_embed ) ) {
						$logger->error( sprintf( 'Error migrating embed %s for post %s: %s', $matches[1], $post_oid, $migrated_embed->get_error_message() ) );
						return $matches[0];
					}

					return $migrated_embed;
				}

				$logger->warning( sprintf( 'Embed %d not found in raw embeds for post %s', $matches[1], $post_oid ) );
				return $matches[0];
			},
			$content
		);

		return $content;
	}

	/**
	 * Migrate audio markers.
	 *
	 * Audio markers in the content are in the format: [audio-N] where N is a 1-based index.
	 * For example: [audio-1] refers to the first audio, [audio-2] to the second, etc.
	 * This method converts these 1-based indices to 0-based indices for array access.
	 *
	 * @param string $post_oid   Post OID.
	 * @param int    $post_id    Post ID.
	 * @param string $content    Post content.
	 * @param string $audio_json_file Raw audios file.
	 * @param array  $post_audio Post audio array (0-based indexed).
	 *
	 * @return string Post content with audio markers replaced by Gutenberg blocks.
	 */
	private function migrate_audio_markers( string $post_oid, int $post_id, string $content, string $audio_json_file, array $post_audio ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$content = preg_replace_callback(
			'/\[audio-(\d+)\]/',
			function ( $matches ) use ( $post_oid, $audio_json_file, $post_id, $logger, $post_audio ) {
				$audio_index = (int) $matches[1] - 1; // Convert to 0-based index.
				if ( ! isset( $post_audio[ $audio_index ] ) ) {
					$logger->warning( sprintf( 'Audio %d not found in post audio for post %s', (int) $matches[1], $post_oid ) );
					return $matches[0];
				}
				$audio_id            = $post_audio[ $audio_index ];
				$possible_raw_audios = iterator_to_array( $this->json_iterator->filtered_items( $audio_json_file, 'oid', $audio_id ) );

				if ( 1 === count( $possible_raw_audios ) ) {
					$raw_audio     = $possible_raw_audios[0];
					$attachment_id = $this->migrate_raw_attachment( $raw_audio, $post_id );

					if ( is_wp_error( $attachment_id ) ) {
						$logger->error( sprintf( 'Error migrating audio %s for post %s: %s', $matches[1], $post_oid, $attachment_id->get_error_message() ) );
						return $matches[0];
					}

					return serialize_block( $this->gutenberg_block_generator->get_audio( get_post( $attachment_id ), $raw_audio->caption ) );
				}

				$logger->warning( sprintf( 'Audio %d not found in raw audios for post %s', $matches[1], $post_oid ) );
				return $matches[0];
			},
			$content
		);

		return $content;
	}

	/**
	 * Migrate PDF markers.
	 *
	 * PDF markers in the content are in the format: [pdf-N] where N is a 1-based index.
	 * For example: [pdf-1] refers to the first PDF, [pdf-2] to the second, etc.
	 * This method converts these 1-based indices to 0-based indices for array access.
	 *
	 * @param string $post_oid  Post OID.
	 * @param int    $post_id   Post ID.
	 * @param string $content   Post content.
	 * @param string $pdf_json_file Raw PDFs file.
	 * @param array  $post_pdfs Post PDFs array (0-based indexed).
	 *
	 * @return string Post content with PDF markers replaced by Gutenberg blocks.
	 */
	private function migrate_pdf_markers( string $post_oid, int $post_id, string $content, string $pdf_json_file, array $post_pdfs ): string {
		$logger = MultiLog::get_cli_and_file_logger( __FUNCTION__ );

		$content = preg_replace_callback(
			'/\[pdf-(\d+)\]/',
			function ( $matches ) use ( $post_oid, $pdf_json_file, $post_id, $logger, $post_pdfs ) {
				$pdf_index = (int) $matches[1] - 1; // Convert to 0-based index.
				if ( ! isset( $post_pdfs[ $pdf_index ] ) ) {
					$logger->warning( sprintf( 'PDF %d not found in post pdfs for post %s', (int) $matches[1], $post_oid ) );
					return $matches[0];
				}
				$pdf_id            = $post_pdfs[ $pdf_index ];
				$possible_raw_pdfs = iterator_to_array( $this->json_iterator->filtered_items( $pdf_json_file, 'oid', $pdf_id ) );

				if ( 1 === count( $possible_raw_pdfs ) ) {
					$raw_pdf       = $possible_raw_pdfs[0];
					$attachment_id = $this->migrate_raw_attachment( $raw_pdf, $post_id );

					if ( is_wp_error( $attachment_id ) ) {
						$logger->error( sprintf( 'Error migrating pdf %s for post %s: %s', $matches[1], $post_oid, $attachment_id->get_error_message() ) );
						return $matches[0];
					}

					// TODO: Check the specialHandling field.
					return serialize_block( $this->gutenberg_block_generator->get_pdf( $attachment_id, $raw_pdf->caption ) );
				}

				$logger->warning( sprintf( 'PDF %d not found in raw pdfs for post %s', $matches[1], $post_oid ) );
				return $matches[0];
			},
			$content
		);

		return $content;
	}

	/**
	 * Migrate raw attachment.
	 *
	 * @param object $raw_attachment Raw attachment.
	 * @param int    $post_id   Post ID.
	 *
	 * @return int|WP_Error Attachment ID or WP_Error.
	 */
	private function migrate_raw_attachment( object $raw_attachment, int $post_id ) {
		$meta_input = [
			'meta_input' => [
				'foundation_oid' => $raw_attachment->oid,
			],
		];

		return Attachments::import_external_file( $raw_attachment->url, null, $raw_attachment->caption, null, $raw_attachment->alt ?? null, $post_id, $meta_input );
	}

	/**
	 * Migrate raw embed.
	 *
	 * @param object $raw_embed Raw embed.
	 *
	 * @return string|WP_Error Embed HTML or WP_Error.
	 */
	private function migrate_raw_embed( object $raw_embed ) {
		$classes = [ 'newspack-embed-container' ];
		$attrs   = [];

		// YouTube embed.
		if ( isset( $raw_embed->hostingProvider ) && 'youtube' === $raw_embed->hostingProvider ) {
			if ( ! isset( $raw_embed->embedURL ) ) {
				return new \WP_Error( 'missing_embed_url', 'Embed URL is missing' );
			}

			return serialize_block( $this->gutenberg_block_generator->get_youtube( $raw_embed->embedURL ) );
		}

		if ( isset( $raw_embed->specialPlacement ) && in_array( 'Info Box', $raw_embed->specialPlacement, true ) ) {
			$classes[] = 'newspack-embed-info-box';
		}

		if ( isset( $raw_embed->alignment ) ) {
			$attrs['align'] = strtolower( $raw_embed->alignment );
			$classes[]      = 'align' . strtolower( $raw_embed->alignment );
		}

		return serialize_block(
			$this->gutenberg_block_generator->get_group_constrained(
				[
					$this->gutenberg_block_generator->get_html( $raw_embed->body ),
				],
				$classes,
				$attrs
			)
		);
	}

	/**
	 * Migrate user bio.
	 *
	 * @param object $user User.
	 * @return string User bio.
	 */
	private function migrate_user_bio( object $user ): string {
		$bio_parts = [];

		if ( ! empty( $user->statusTagline ) ) {
			$bio_parts[] = $user->statusTagline;
		}

		if ( ! empty( $user->bio ) ) {
			$bio_parts[] = $user->bio;
		}

		return implode( "\n\n", $bio_parts );
	}

	/**
	 * Maps Foundation post status to WordPress post status.
	 *
	 * @param string $status Foundation post status.
	 * @return string WordPress post status.
	 */
	private function map_post_status( string $status ): string {
		switch ( $status ) {
			case 'Live':
				return 'publish';
			case 'Draft':
				return 'draft';
			case 'Pending Review':
				return 'pending';
			case 'Offline':
				return 'trash';
			case 'Scheduled':
				return 'future';
			default:
				return 'publish';
		}
	}

	/**
	 * Maps Foundation author to WordPress author.
	 *
	 * @param array $authors Foundation authors.
	 * @return array WordPress author ID.
	 */
	private function map_authors( array $authors ): array {
		$all_authors  = $this->load_authors();
		$post_authors = [];

		foreach ( $authors as $author ) {
			if ( array_key_exists( $author, $all_authors ) ) {
				$post_authors[ $author ] = (int) $all_authors[ $author ];
			}
		}

		return $post_authors;
	}

	/**
	 * Maps Foundation categories to WordPress categories.
	 *
	 * @param array $categories Foundation categories.
	 * @return array WordPress category IDs.
	 */
	private function map_categories( array $categories ): array {
		$all_categories  = $this->load_taxonomies( Taxonomy::UNIQUE_CATEGORY_IDENTIFIER_META_KEY );
		$post_categories = [];

		foreach ( $categories as $category ) {
			if ( array_key_exists( $category, $all_categories ) ) {
				$post_categories[ $category ] = (int) $all_categories[ $category ];
			}
		}

		return $post_categories;
	}

	/**
	 * Loads authors from the database.
	 *
	 * @return array Authors.
	 */
	private function load_authors(): array {
		global $wpdb;

		$authors = [];

		// @phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$user_meta = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT user_id, meta_value FROM {$wpdb->usermeta} WHERE meta_key = %s",
				[ UsersHelper::UNIQUE_IDENTIFIER_META_KEY ]
			)
		);

		foreach ( $user_meta as $user_meta_item ) {
			$authors[ $user_meta_item->meta_value ] = $user_meta_item->user_id;
		}

		return $authors;
	}

	/**
	 * Loads categories from the database.
	 *
	 * @param string $taxonomy_identifier_meta_key Taxonomy identifier meta key.
	 *
	 * @return array Categories.
	 */
	private function load_taxonomies( string $taxonomy_identifier_meta_key ): array {
		global $wpdb;

		$categories = [];

		// @phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$term_meta = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT term_id, meta_value FROM {$wpdb->termmeta} WHERE meta_key = %s",
				[ $taxonomy_identifier_meta_key ]
			)
		);

		foreach ( $term_meta as $term_meta_item ) {
			$categories[ $term_meta_item->meta_value ] = $term_meta_item->term_id;
		}

		return $categories;
	}
}
